// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.Migrations
{
    [DbContext(typeof(MMContext))]
    [Migration("20200503131608_MonitorMe-FirstMigration")]
    partial class MonitorMeFirstMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Models.AlarmLog", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MonitorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MonitorId");

                    b.ToTable("log.AlarmLog");
                });

            modelBuilder.Entity("Models.Monitor", b =>
                {
                    b.Property<string>("MonitorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("LastBeat")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("MaxInterval")
                        .HasColumnType("time");

                    b.Property<string>("MonitorGroupId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("MonitorId");

                    b.HasIndex("MonitorGroupId");

                    b.ToTable("dbo.Monitor");
                });

            modelBuilder.Entity("Models.MonitorGroup", b =>
                {
                    b.Property<string>("MonitorGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(30)")
                        .HasMaxLength(30);

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("MonitorGroupId");

                    b.ToTable("dbo.MonitorGroup");
                });

            modelBuilder.Entity("Models.SysLog", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("log.SysLog");
                });

            modelBuilder.Entity("Models.AlarmLog", b =>
                {
                    b.HasOne("Models.Monitor", "Monitor")
                        .WithMany()
                        .HasForeignKey("MonitorId");
                });

            modelBuilder.Entity("Models.Monitor", b =>
                {
                    b.HasOne("Models.MonitorGroup", "MonitorGroup")
                        .WithMany()
                        .HasForeignKey("MonitorGroupId");
                });
#pragma warning restore 612, 618
        }
    }
}
